version: "3.9"
services:
  todo_api:
    build: .
    container_name: todo_list_app
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
